language: c

install:
  # install json-c
  - sudo apt-get install build-essential
  - sudo apt-get install libtool
  - git clone https://github.com/json-c/json-c
  - cd json-c
  - sh autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - sudo apt-get install -qq libmicrohttpd-dev libgnutls-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make